solve the licensing problem of nagfor; add path for ftest and vtest on Kunpeng; remove gtest from Kunpeng

diff --git a/.github/workflows/test_nagfor.yml b/.github/workflows/test_nagfor.yml
--- a/.github/workflows/test_nagfor.yml
+++ b/.github/workflows/test_nagfor.yml
@@ -21,4 +21,6 @@ jobs:
 
       - name: Conduct the test
         run: |
+          export PATH=$PATH:"~/local/bin"
+          source ~/local/bin/nag_licensing || echo "\n\nNAG licensing failed.\n\n"
           cd test && make ntest
